[Service]
# ORÓMA – ASR: whisper.cpp (kein venv, kein torch)
Environment=OROMA_ASR_BACKEND=whispercpp
Environment=OROMA_WHISPER_ENABLE=false

# Audio Input: Jabra Speak2 55 MS ist bei dir index 0
#Environment=OROMA_AUDIO_INPUT_INDEX=0
