[Service]
Environment="OROMA_SERVICE_ALLOW=oroma,oroma-replay"
Environment="OROMA_SERVICE_PREFIX=oroma"
Environment="OROMA_ALLOW_REBOOT=1"
Environment="OROMA_SERVICECTL_CMD=/usr/bin/sudo /usr/bin/systemctl"
Environment="OROMA_REBOOT_CMD=/usr/bin/sudo /usr/bin/systemctl reboot"