# /etc/systemd/system/oroma.service.d/40-camera.conf
[Service]
# libcamera Logs zusätzlich in Datei ablegen (optional)
Environment=LIBCAMERA_LOG_LEVELS=*:2
Environment=LIBCAMERA_LOG_FILE=/opt/ai/oroma/logs/libcamera.log